openapi: "3.0.2"
info:
  title: Basic swagger setup for REST Test API
  version: "1.0"
servers:
  - url: http://localhost:5000
tags:
  - name: Tests
  - name: Users
paths:
  /test:
    get:
      summary: Hello world
      tags:
        - "Tests"
      responses:
        "200":
          description: OK

  /test/{name}:
    get:
      summary: Personalised greeting
      tags:
        - "Tests"
      description: Returns Hello with your name
      responses:
        "200":
          description: OK
      parameters:
        - name: name
          in: path
          description: enter your name here
          required: true
          schema:
            type: string

  /users:
    post:
      summary: User login endpoint
      tags:
        - "Users"
      description: Returns user details with json token
      requestBody:
        content:
          "application/json":
            schema:
              properties:
                email:
                  description: User name
                  type: string
                password: 
                  description: User password
                  type: string
              required:
                - password
                - email
      responses:
        "200":
          description: OK
          content:
            "application/json": {}
        "405":
          description: Method Not Allowed
          content:
            "application/json": {}
            "application/xml": {}
